INSERT INTO exercises (name, is_custom, category) VALUES
    ('Push-Up', FALSE, 'CHEST'),
    ('Pull-Up', FALSE, 'BACK'),
    ('Squat', FALSE, 'LEGS'),
    ('Bicep Curl', FALSE, 'ARMS'),
    ('Shoulder Press', FALSE, 'SHOULDERS'),
    ('Plank', FALSE, 'CORE'),
    ('Deadlift', FALSE, 'BACK'),
    ('Lunges', FALSE, 'LEGS'),
    ('Bench Press', FALSE, 'CHEST'),
    ('Triceps Dip', FALSE, 'ARMS'),
    ('Leg Press', FALSE, 'LEGS'),
    ('Lat Pulldown', FALSE, 'BACK'),
    ('Chest Fly', FALSE, 'CHEST'),
    ('Russian Twist', FALSE, 'CORE'),
    ('Glute Bridge', FALSE, 'GLUTES'),
    ('Mountain Climbers', FALSE, 'CORE'),
    ('Dumbbell Row', FALSE, 'BACK'),
    ('Overhead Tricep Extension', FALSE, 'ARMS'),
    ('Calf Raise', FALSE, 'LEGS'),
    ('Burpees', FALSE, 'GENERAL');
